<x-layouts::app :title="__('Gfa Admin')">
    <div class="gfa-admin-page flex min-h-full w-full flex-1 flex-col gap-6 pb-8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        <style>
            .gfa-admin-page .tabs{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;border-bottom:2px solid #e8e8f0;margin-bottom:22px;background:#fff;padding:0 8px}
            .gfa-admin-page .tab{border:none;background:transparent;color:#6c757d;font-size:14px;font-weight:600;padding:12px 16px;border-bottom:3px solid transparent;margin-bottom:-2px;display:inline-flex;align-items:center;gap:8px;cursor:pointer}
            .gfa-admin-page .tab.active{color:#4B49AC;border-bottom-color:#4B49AC}
            .gfa-admin-page .pane{display:none}.gfa-admin-page .pane.active{display:block}
            .gfa-admin-page .gfa-card{background:#fff;border-radius:12px;box-shadow:0 2px 12px rgba(0,0,0,.06);padding:24px;max-width:1100px;margin:0 auto 20px;border:1px solid #ececf5}
            .gfa-admin-page .gfa-card h3{font-size:20px;font-weight:700;color:#191C24;display:flex;gap:10px;justify-content:center;margin:0 0 18px}
            .gfa-admin-page .controls{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:16px;background:#fcfcff;padding:15px;border-radius:8px}
            .gfa-admin-page .input,.gfa-admin-page .controls select,.gfa-admin-page .controls input[type="date"]{width:100%;border:1px solid #dee2e6;border-radius:8px;padding:8px 12px;font-size:13px;min-height:38px;box-sizing:border-box}
            .gfa-admin-page .btn{border:none;border-radius:7px;padding:8px 14px;font-size:13px;font-weight:600;cursor:pointer;display:inline-flex;align-items:center;gap:8px}
            .gfa-admin-page .btn-primary{background:#4B49AC;color:#fff}.gfa-admin-page .btn-add{background:#28a745;color:#fff}.gfa-admin-page .btn-danger{background:#dc3545;color:#fff}
            .gfa-admin-page .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 16px}.gfa-admin-page .form-actions{margin-top:12px;display:flex;justify-content:flex-end}
            .gfa-admin-page .table-wrap{overflow:auto;border:1px solid #ececf5;border-radius:12px}.gfa-admin-page .table{width:100%;border-collapse:collapse}.gfa-admin-page .table th,.gfa-admin-page .table td{padding:12px 14px;border-top:1px solid #eef0f3;text-align:left;font-size:13px}.gfa-admin-page .table th{background:#f8f9ff;border-top:none;font-size:12px}
            .gfa-admin-page .stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.gfa-admin-page .stat{background:#f8f9ff;border:1px solid #ececf5;border-radius:10px;padding:15px 10px;text-align:center}.gfa-admin-page .muted{color:#888;font-size:13px}.gfa-admin-page .center{text-align:center}.gfa-admin-page .empty{padding:24px;color:#aaa;text-align:center}
            .gfa-admin-page .status{display:none;padding:10px;border-radius:8px;font-size:13px;margin-bottom:12px}.gfa-admin-page .ok{background:#e8f7ef;color:#146c43}.gfa-admin-page .err{background:#fdecea;color:#842029}
            @media (max-width:992px){.gfa-admin-page .grid,.gfa-admin-page .stats{grid-template-columns:1fr}}
        </style>

        <div class="center" style="margin-bottom:25px;">
            <h1 style="margin:0;font-weight:700;display:flex;justify-content:center;gap:10px;"><i class="fas fa-layer-group" style="color:#4B49AC"></i>Gfa Admin</h1>
        </div>

        <div class="tabs">
            <button class="tab active" data-pane="global"><i class="fas fa-chart-bar"></i> Vue globale</button>
            <button class="tab" data-pane="services"><i class="fas fa-briefcase"></i> Services</button>
            <button class="tab" data-pane="guichets"><i class="fas fa-desktop"></i> Guichets</button>
            <button class="tab" data-pane="agents"><i class="fas fa-user-tie"></i> Agents</button>
            <button class="tab" data-pane="tickets"><i class="fas fa-ticket-alt"></i> Tickets</button>
            <button class="tab" data-pane="parametres"><i class="fas fa-cog"></i> Parametres</button>
            <button class="tab" data-pane="ecran"><i class="fas fa-tv"></i> Ecran</button>
        </div>

        <div id="global" class="pane active"><div class="gfa-card"><h3><i class="fas fa-chart-line"></i> Statistiques Temps Reel</h3><div id="stats-box"></div></div></div>

        <div id="services" class="pane"><div class="gfa-card"><h3><i class="fas fa-briefcase"></i> Gestion des services</h3><div class="controls"><input id="service-search" class="input" placeholder="Rechercher un service..." style="max-width:300px"></div><div id="service-status" class="status"></div><div class="grid"><div><label>Nom du service *</label><input id="service-name" class="input"></div><div><label>Prefixe</label><input id="service-prefix" class="input"></div></div><div class="form-actions"><button class="btn btn-add" type="button" onclick="createService()"><i class="fas fa-plus"></i> Enregistrer</button></div><div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>Nom</th><th>Prefixe</th></tr></thead><tbody id="services-body"></tbody></table></div></div></div>

        <div id="guichets" class="pane"><div class="gfa-card"><h3><i class="fas fa-desktop"></i> Configuration des guichets</h3><div class="controls"><input id="guichet-search" class="input" placeholder="Rechercher un guichet..." style="max-width:300px"></div><div id="guichet-status" class="status"></div><div class="grid"><div><label>Numero *</label><input id="guichet-numero" class="input"></div><div><label>Informations</label><input id="guichet-infos" class="input"></div><div style="grid-column:1/-1"><label>Service rattache</label><select id="guichet-service" class="input"><option value="">Aucun</option></select></div></div><div class="form-actions"><button class="btn btn-add" type="button" onclick="createGuichet()"><i class="fas fa-plus"></i> Enregistrer</button></div><div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>Numero</th><th>Informations</th><th>Service</th></tr></thead><tbody id="guichets-body"></tbody></table></div></div></div>

        <div id="agents" class="pane"><div class="gfa-card"><h3><i class="fas fa-user-tie"></i> Liste des agents</h3><div class="controls"><input id="agent-search" class="input" placeholder="Rechercher un agent..." style="max-width:300px"></div><div id="agent-status" class="status"></div><div class="grid"><div><label>Nom *</label><input id="agent-nom" class="input"></div><div><label>Prenom</label><input id="agent-prenom" class="input"></div><div><label>Service *</label><select id="agent-service" class="input"></select></div><div><label>Guichet *</label><select id="agent-guichet" class="input"></select></div></div><div class="form-actions"><button class="btn btn-add" type="button" onclick="createAgent()"><i class="fas fa-plus"></i> Enregistrer</button></div><div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>Nom</th><th>Prenom</th><th>Service</th><th>Guichet</th></tr></thead><tbody id="agents-body"></tbody></table></div></div></div>

        <div id="tickets" class="pane"><div class="gfa-card"><h3><i class="fas fa-ticket-alt"></i> Suivi des tickets</h3><div class="controls"><input id="ticket-search" class="input" placeholder="Rechercher..." style="flex:1;min-width:200px"><select id="filter-guichet" style="width:auto"></select><select id="filter-statut" style="width:auto"><option value="">Tous statuts</option><option value="EN_ATTENTE">En attente</option><option value="EN_COURS">En cours</option><option value="TERMINE">Termine</option><option value="INCOMPLET">Incomplet</option><option value="ABSENT">Absent</option></select><input type="date" id="filter-date" style="width:auto"><button type="button" class="btn btn-add" onclick="exportTickets()"><i class="fas fa-file-excel"></i> Export Excel</button><button type="button" class="btn btn-danger" onclick="truncateTickets()"><i class="fas fa-trash"></i> Vider tickets</button></div><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Numero</th><th>Service</th><th>Guichet</th><th>Agent</th><th>Creation</th><th>Statut</th></tr></thead><tbody id="tickets-body"></tbody></table></div></div></div>

        <div id="parametres" class="pane"><div class="gfa-card"><h3><i class="fas fa-wifi"></i> Parametres Wi-Fi</h3><p class="muted center">Configuration du point d'acces pour le QR Code de l'ecran public.</p><form action="/facturation/gfa-admin/wifi-settings" method="post" style="max-width:500px;margin:20px auto;display:grid;gap:16px">@csrf<div><label>Nom du reseau (SSID)</label><input name="ssid" class="input" required placeholder="Ex: DakarTerminal_Guest"></div><div><label>Mot de passe</label><input type="password" name="password" class="input" placeholder="Laisser vide si ouvert"></div><button type="submit" class="btn btn-primary" style="justify-content:center"><i class="fas fa-save"></i> Enregistrer les parametres</button></form></div></div>

        <div id="ecran" class="pane"><div class="gfa-card center"><h3><i class="fas fa-tv"></i> Affichage Public</h3><p class="muted" style="margin-bottom:25px;">Lancer l'interface de file d'attente pour les ecrans du hall.</p><a class="btn btn-primary" href="/gfa/display" target="_blank">Ouvrir l'ecran d'appel</a></div></div>

        <script>
            const store = { services: [], guichets: [], agents: [], tickets: [], stats: [] };
            const $ = id => document.getElementById(id);
            const lower = v => (v || '').toString().toLowerCase();
            const fmt = v => v || '-';
            const showStatus = (id, msg, ok) => { const el = $(id); el.textContent = msg; el.className = `status ${ok ? 'ok' : 'err'}`; el.style.display = 'block'; };
            const json = async url => { const r = await fetch(url); if (!r.ok) throw new Error('api'); return await r.json(); };
            const tabs = document.querySelectorAll('.tab');
            tabs.forEach(t => t.addEventListener('click', () => { tabs.forEach(x => x.classList.remove('active')); document.querySelectorAll('.pane').forEach(p => p.classList.remove('active')); t.classList.add('active'); $(t.dataset.pane).classList.add('active'); }));
            function syncOptions() { $('guichet-service').innerHTML = '<option value="">Aucun</option>' + store.services.map(s => `<option value="${s.id}">${s.nom}</option>`).join(''); $('agent-service').innerHTML = store.services.map(s => `<option value="${s.id}">${s.nom}</option>`).join(''); $('agent-guichet').innerHTML = store.guichets.map(g => `<option value="${g.id}">${g.numero}</option>`).join(''); $('filter-guichet').innerHTML = '<option value="">Tous les guichets</option>' + store.guichets.map(g => `<option value="${g.id}">${g.numero}</option>`).join(''); }
            function renderStats() { $('stats-box').innerHTML = store.stats.length ? store.stats.map(s => `<div style="margin-bottom:25px"><div style="font-size:12px;font-weight:800;letter-spacing:1px;color:#4B49AC;margin-bottom:12px;text-transform:uppercase;text-align:left;padding-left:5px;border-left:4px solid #4B49AC;">${s.serviceNom}</div><div class="stats"><div class="stat"><div class="muted">Attente</div><div style="font-size:24px;font-weight:800">${s.enAttente}</div></div><div class="stat"><div class="muted">En cours</div><div style="font-size:24px;font-weight:800">${s.enCours}</div></div><div class="stat"><div class="muted">Termines</div><div style="font-size:24px;font-weight:800">${s.termine}</div></div><div class="stat"><div class="muted">Incomplets</div><div style="font-size:24px;font-weight:800">${s.incomplet}</div></div><div class="stat"><div class="muted">Absents</div><div style="font-size:24px;font-weight:800">${s.absent}</div></div></div></div>`).join('') : '<p class="empty">Aucune donnee disponible.</p>'; }
            function renderServices() { const q = lower($('service-search').value); const rows = store.services.filter(s => lower(s.nom).includes(q) || lower(s.prefixe).includes(q)); $('services-body').innerHTML = rows.length ? rows.map(s => `<tr><td>${fmt(s.nom)}</td><td>${fmt(s.prefixe)}</td></tr>`).join('') : '<tr><td colspan="2" class="empty">Aucun service</td></tr>'; }
            function renderGuichets() { const q = lower($('guichet-search').value); const rows = store.guichets.filter(g => [g.numero, g.infos, g.serviceNom].some(v => lower(v).includes(q))); $('guichets-body').innerHTML = rows.length ? rows.map(g => `<tr><td>${fmt(g.numero)}</td><td>${fmt(g.infos)}</td><td>${fmt(g.serviceNom)}</td></tr>`).join('') : '<tr><td colspan="3" class="empty">Aucun guichet</td></tr>'; }
            function renderAgents() { const q = lower($('agent-search').value); const rows = store.agents.filter(a => [a.nom, a.prenom, a.serviceNom, a.guichetNumero].some(v => lower(v).includes(q))); $('agents-body').innerHTML = rows.length ? rows.map(a => `<tr><td>${fmt(a.nom)}</td><td>${fmt(a.prenom)}</td><td>${fmt(a.serviceNom)}</td><td>${fmt(a.guichetNumero)}</td></tr>`).join('') : '<tr><td colspan="4" class="empty">Aucun agent</td></tr>'; }
            function renderTickets() { const q = lower($('ticket-search').value); const rows = store.tickets.filter(t => [t.id, t.numero, t.serviceNom, t.guichetNumero, t.agentNom, t.statut].some(v => lower(v).includes(q))); $('tickets-body').innerHTML = rows.length ? rows.map(t => `<tr><td>${fmt(t.id)}</td><td>${fmt(t.numero)}</td><td>${fmt(t.serviceNom)}</td><td>${fmt(t.guichetNumero)}</td><td>${fmt(t.agentNom)}</td><td>${t.createdAt ? new Date(t.createdAt).toLocaleString('fr-FR') : '-'}</td><td>${fmt(t.statut)}</td></tr>`).join('') : '<tr><td colspan="7" class="empty">Aucun ticket</td></tr>'; }
            async function createService() { try { await fetch('/gfa/api/services', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ nom:$('service-name').value.trim(), prefixe:$('service-prefix').value.trim() }) }); showStatus('service-status', 'Service ajoute avec succes.', true); await loadServices(); } catch (e) { showStatus('service-status', 'Erreur lors de la creation.', false); } }
            async function createGuichet() { try { await fetch('/gfa/api/guichets', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ numero:$('guichet-numero').value.trim(), infos:$('guichet-infos').value.trim(), serviceId:$('guichet-service').value || null }) }); showStatus('guichet-status', 'Guichet ajoute avec succes.', true); await loadGuichets(); await loadAgents(); } catch (e) { showStatus('guichet-status', 'Erreur lors de la creation.', false); } }
            async function createAgent() { try { await fetch('/gfa/api/agents', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ nom:$('agent-nom').value.trim(), prenom:$('agent-prenom').value.trim(), serviceId:$('agent-service').value || null, guichetId:$('agent-guichet').value || null }) }); showStatus('agent-status', 'Agent ajoute avec succes.', true); await loadAgents(); } catch (e) { showStatus('agent-status', 'Erreur lors de la creation.', false); } }
            async function exportTickets() { const params = new URLSearchParams(); if ($('filter-guichet').value) params.set('guichetId', $('filter-guichet').value); if ($('filter-statut').value) params.set('statut', $('filter-statut').value); if ($('filter-date').value) params.set('date', $('filter-date').value); const res = await fetch('/gfa/api/tickets/export' + (params.toString() ? '?' + params.toString() : '')); if (!res.ok) { await Swal.fire({ icon:'error', title:'Erreur', text:'Impossible de telecharger le fichier Excel.' }); return; } const blob = await res.blob(); const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `tickets-gfa-${new Date().toISOString().slice(0,10)}.xlsx`; document.body.appendChild(a); a.click(); a.remove(); window.URL.revokeObjectURL(url); }
            async function truncateTickets() { const result = await Swal.fire({ title:'Vider tous les tickets ?', text:'Cette action supprimera definitivement tous les tickets.', icon:'warning', showCancelButton:true, confirmButtonText:'Oui, vider', cancelButtonText:'Annuler', confirmButtonColor:'#dc3545' }); if (!result.isConfirmed) return; const response = await fetch('/gfa/api/tickets/truncate', { method:'DELETE' }); if (!response.ok) { await Swal.fire({ icon:'error', title:'Erreur', text:'La suppression des tickets a echoue.' }); return; } await Swal.fire({ icon:'success', title:'Succes', text:'La table des tickets a ete videe.' }); await loadTickets(); await loadStats(); }
            async function loadServices() { store.services = await json('/gfa/api/services'); syncOptions(); renderServices(); }
            async function loadGuichets() { store.guichets = await json('/gfa/api/guichets'); syncOptions(); renderGuichets(); }
            async function loadAgents() { store.agents = await json('/gfa/api/agents'); renderAgents(); }
            async function loadStats() { store.stats = await json('/gfa/api/stats'); renderStats(); }
            async function loadTickets() { const params = new URLSearchParams(); if ($('filter-guichet').value) params.set('guichetId', $('filter-guichet').value); if ($('filter-statut').value) params.set('statut', $('filter-statut').value); if ($('filter-date').value) params.set('date', $('filter-date').value); store.tickets = await json('/gfa/api/tickets' + (params.toString() ? '?' + params.toString() : '')); renderTickets(); }
            $('service-search').addEventListener('input', renderServices); $('guichet-search').addEventListener('input', renderGuichets); $('agent-search').addEventListener('input', renderAgents); $('ticket-search').addEventListener('input', renderTickets); $('filter-guichet').addEventListener('change', loadTickets); $('filter-statut').addEventListener('change', loadTickets); $('filter-date').addEventListener('change', loadTickets);
            window.onload = async () => { await Promise.all([loadServices(), loadGuichets(), loadAgents(), loadStats(), loadTickets()]); };
        </script>
    </div>
</x-layouts::app>
